* Old code
** old test helper code
(defn normalize [tmsg*]
  (->> tmsg*
       (postwalk (fn [x] (if (number? x) (float x) x)))
       (map (fn [[t m]] [t (set m)]))))

(defn eq? [a b]
  (= (normalize a) (normalize b)))

(defn pprint-timestamped-msg* [tmsg*]
  (doseq [[t msg] tmsg*] (println (format "[%.3f] %s" (float t) msg))))

* DEVS
** DONE Explain current issue
   - Dynamic updates aren't working.
   - I think the order of operations is messed up, and the exec is reset before
     it emits network change messages.

   - The problem is that the network exec is receiving messages, which makes it
     activated, which causes triggers its network structure output, which was
     premature.
     - It shouldn't be receiving messages. Something is wrong with the routes.
** Refactor
   - No execs.
   - Any model can send network structure messages.
   - Network structure messages are sent like any other message.
   - Networks are defined with an initial structure.
   - Network structure messages are handled after other messages.
   - Update test to wait a cycle before sending job message to new worker.
*** Consider using the regular mail for network structure messages.
    - Note that we already aren't using exec to store network structure.
**** pros/cons
      - one message channel
      - No need to distinguish execs from atomic models, which may be more
        efficient.
**** Proposal
      - Implicit connection between network and each model.
** Fix issues
*** rem-model needs to handle all types of models
**** networks
     - Problem: network models aren't currently stored.
       - We depend on that for terminal? in route.
**** executives
     - Recursively remove.
*** disconnect - prune dead branches
    - Determine if this
** Add more tests.
   - Use examples.
   - Confluence tests.
   - Verify that parallel is working properly.
   - Try some tricky situations.
*** Create an example for benchmarking.
** Consider improvements
*** Consider if sender message order should be preserved.
    - Meaning, the order on the receivers end preserved.
    - This was an explicit assumption in one of the papers.
*** Consider if there is any advantage to separating network routes from internal routes.
*** Consider using a parent lookup
    - Might simplify network checks, too.
*** Use a special symbol for :network.
*** Rename the state that is {:model :state :tl :tn} to something else.
*** Don't return total state as one fn.
    - Separate out returning the initial elapsed-time and make it default to 0.
*** Consider not passing both the records and state to the IModel fns.
    - It's redundant.
    - Need to determine what is clearer.
    - Still need to record tl and tn.
*** Add constructor and destructor to models.
** Implement a RT root coordinator.
   - Refer to file:///home/austin/projects/tomato-system/doc/papers/devsjava_2005.pdf
     - p. 89
     - The root coordinator gates child processes.

   - http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.843.6421&rep=rep1&type=pdf
     - Section 4.1: How to avoid accumulating delays due to actual execution
       time.
       - See last paragraph.
*** Test replaying an input history.
** Delete old code.
** update docs
*** time
    - Need to be clear about how parallelization means that everything needs to
      treat events occuring at the same time as simultaneous, but not the
      different phases.
*** Consider my notes on graph paper about different categories of functions.
    - behavior (int-update, etc.)
    - structure (add-lp, connect, etc.)
    - communication (send, receive)
*** Document network structure messages
*** update README
*** update tutorial
*** Put this documentation somewhere

  The core of a root-simulator, but without an \"update driver\".

  This core provides a priority-queue for scheduling future events, and a step
  function to update the simulation based on the next event, which may be
  internal, external, or both simultaneously.

  A complete root-simulator implementation depends on the platform and
  requirements. Some examples:

  - An \"as-fast-as-possible\" simulator may run through an entire simulation in a single loop.
  - A Real-Time simulator might synchronize the updates with a real-time clock.
  - In the browser, a Real-Time simulator might use setInterval or updateAnimationFrame to drive the updates.
  - On the JVM, a Real-Time simulator might use threads.

  All cases need a way to schedule future events and all cases use the same
  logic for determining the next event and processing it.

  Note that \"simulator\" is synonymous with \"coordinator\". A coordinator is a
  simulator associated with a coupled model. A coupled model may also be
  referred to as a network model.

  The symbols "key", "k", "k1", etc. are synonomous with "model name".

*** Why not use protocols for models?
    - Don't know how to use a default implementation for the confluent function.
      - Note that it also depends on two of the other fn implementations.
    - The record would implement part of the simulator: maintaining state and
      tl, tn, but this would preclude flattening the network (and maybe other
      types of static analysis).
*** names
    - A model name can be anything that can be compared for equality. Keywords,
      symbols, and strings are good choices.
*** abstract simulators
    - These are meant to be mathematical structures, but we can also implement
      them. But don't get too attached to an implementation; others are always
      possible.
      - For example, we could change all the function calls to use some
        asynchronous method, and as long as we implement callbacks or whatever
        to keep the model in tact, that is ok.
*** if we do our own system
    - Say what we borrowed from where.
      - e.g., separation of model and simulator from DEVS
*** Make notes about optimizations.
 #_
 (defn route
   "Converts snd-name->snd-port->vs to rcv-name->rcv-port->vs based on routes."
   [pkg snd-name->snd-port->vs]
   (let [routes    (:routes pkg)
         flattened (for [[snd-name snd-port->vs] snd-name->snd-port->vs
                         [snd-port vs]           snd-port->vs
                         [rcv-name rcv-port->fs] (get-in routes [snd-name snd-port])
                         [rcv-port fs]           rcv-port->fs
                         f                       fs]
                     [rcv-name rcv-port (map f vs)])]
     (reduce (fn [m [rcv-name rcv-port vs]]
               ;;(update-in m [rcv-name rcv-port] into (map f) vs) ;; Alt transducer version, if we didn't apply map already.
               (update-in m [rcv-name rcv-port] into vs))
             {}
             flattened)))
 #_
 (defn route-1
   "Converts snd-name->snd-port->vs to rcv-name->rcv-port->vs based on routes."
   [routes snd-name->snd-port->vs]
   (reduce (fn [m [rcv-name rcv-port f vs]]
             (update-in m [rcv-name rcv-port] into (map f) vs))
           {}
           (for [[snd-name snd-port->vs] snd-name->snd-port->vs
                 [snd-port vs]           snd-port->vs
                 [rcv-name rcv-port->fs] (get-in routes [snd-name snd-port])
                 [rcv-port fs]           rcv-port->fs
                 f                       fs]
             [rcv-name rcv-port f vs])))

 (defn alt-route
   "Converts snd-name->snd-port->vs to rcv-name->rcv-port->vs based on routes."
   [pkg mail]
   (let [sn->sp->rn->rp->fs (:routes pkg)
         sn->sp->vs         mail]
     ;; For each sender sending mail,
     (reduce-kv (fn [m sn sp->vs]
                  ;; Get all routes from sender,
                  (let [sp->rn->rp->fs (sn->sp->rn->rp->fs sn)]
                    ;; For each port mail is being sent on,
                    (reduce-kv (fn [m sp vs]
                                 ;; Get all the receivers connected to that port,
                                 (let [rn->rp->fs (sp->rn->rp->fs sp)]
                                   ;; For each receiver,
                                   (reduce-kv (fn [m rn rp->fs]
                                                ;; For each port the receiver is connected on,
                                                (assoc m
                                                       (reduce-kv (fn [m rp fs]
                                                                    ;; For each input function applied to this connection,
                                                                    (reduce (fn [m f]
                                                                              (update m rp into (map f vs)))
                                                                            m
                                                                            fs))
                                                                  (get m rn {})
                                                                  rp->fs)))
                                              m
                                              rn->rp->fs)))
                               m
                               sp->vs)))
                {}
                sn->sp->vs)))

**** use these comments

 ;;------------------------------------------------------------------------------

 ;; We shouldn't restrict connections, because compressed routes may violate
 ;; those restrictions.
 #_
 (defn connect
   [pkg [snd-name snd-port rcv-name rcv-port input-fn]]
   ;; In the connections graph, nodes are [name port] pairs (not models!). A path
   ;; between two models is either simple: between two atomic models in the same
   ;; network, or it may be composed of multiple segments that span networks.

   ;; A proper path suffix is a path that terminates in an atomic model.

   ;; fwd is a trie and a DAG. Each path in the trie represents one forward edge
   ;; in the DAG. The height of the DAG is equal to the depth of the network
   ;; hierarchy. The graph may contain incomplete paths, which start and/or end
   ;; with a network.

   ;; opt is a compressed version of fwd. The opt DAG has depth = 1. opt replaces
   ;; each proper suffix path in fwd with a single compressed edge from the
   ;; current node to a terminal node.

   ;; For example, if fwd = {A-B, B-C, C-D}, then opt = {A-D, B-D, C-D}.

   ;; If D is a network, however, then opt = {}, because there are no paths from
   ;; any node to a terminal.

   ;; opt really is {A-D_1, B-D_1, C-D_1}, because there can be more than one
   ;; path from a node to another.

   ;; The basic idea is to get all of the suffix paths below the new
   ;; connection, if there are any, and then start moving up,
   ;; following the reverse graph, recording compressed connections.

   ;; We may need another data structure to map from component-fns ->
   ;; combined-fns, to support delete, since we can't expect function
   ;; compositions to compare equally.

   (let [network? (fn [x] (not (contains? (:state pkg) x)))]
     ;; Use paths as canonical names for models in a flattened
     ;; hierarchy. Substitute internal :network references with the model's
     ;; external name.
     (let [snd-path (if (= :network snd-name)
                      *path*
                      (conj *path* snd-name))
           rcv-path (if (= :network rcv-name)
                      *path*
                      (conj *path* rcv-name))]
       (let [{:keys [fwd rev opt]} pkg]
         (let [fwd (assoc-in fwd [snd-path snd-port rcv-path rcv-port] input-fn)
               rev (assoc-in rev [rcv-path rcv-port snd-path snd-port] input-fn)
               ;; Propagate compressed paths up through the network. This is an
               ;; online algorithm. It precomputes all of the path traversals.

               ;; Use a prefix table and a suffix table. That will be easier to
               ;; understand.

               ;; Find each set and compute prefixes X [new] x suffixes.

               ;; The tradeoff with this approach is the memory use and the
               ;; maintenance of the prefix and suffix tables, with no guarantee
               ;; that any of it will ever be needed. This may be optimal for
               ;; some simulations.

               ;; For example, there could be a signal that originates deep
               ;; inside a model and travels deep down into many others, but the
               ;; signal is rare, like an alarm. It could require a lot of work
               ;; to build all of those connections and they may never be used.

               ;; How could this be lazy?

               ;; Would it be better to cache routes?

               ;; We should abstract this API. There isn't a one-size-fits-all
               ;; implementation. We just need connect, disconnect, and route.

               ;; Also, optimizing this lookup is not the main reason to flatten
               ;; the hierarchy, parallel updates is.

               ;; This could be even more efficient through static analysis of
               ;; the network topology: all possible models, ports, connections,
               ;; etc.

               ;; The simple method needs to batch values at each step of the
               ;; traversal.


               opt (loop [connections (cond
                                        ;; If the new connection terminates at a network,
                                        ;; get any compressed paths rooted there, and
                                        ;; extend each with this new segment.
                                        (network? rcv-path) (for [[rcv-path' rcv-port'->fs] (get-in opt [rcv-path rcv-port])
                                                                  [rcv-port' fs]            rcv-port'->fs
                                                                  f                         fs]
                                                              [snd-path snd-port rcv-path' rcv-port' (comp f input-fn)])
                                        ;; If the new connection terminates at an atomic
                                        ;; model, then it is already compressed.
                                        :else               [[snd-path snd-port rcv-path rcv-port input-fn]])
                          opt         opt]
                     (if (empty? connections)
                       opt
                       (let [[snd-path snd-port rcv-path rcv-port input-fn] (first connections)
                             opt                                            (update-in opt [snd-path snd-port rcv-path rcv-port] (fnil conj #{}) input-fn)
                             connections                                    (into (rest connections)
                                                                                  (for [[snd-path' snd-port'->fs] (get-in rev [snd-path snd-port])
                                                                                        [snd-port' fs]            snd-port'->fs
                                                                                        f                         fs]
                                                                                    [snd-path' snd-port' rcv-path rcv-port (comp input-fn f)]))]
                         (recur connections opt))))]
          (assoc pkg
                 :fwd fwd
                 :rev rev
                 :opt opt))))))
 #_
 (defn route-mail
   "Converts sender->port->vs to receiver->port->vs based on routes."
   [routes sender->port->vs]
   (let [flattened (for [[sender port->vs]      sender->port->vs
                         [out-port vs]          port->vs
                         [receiver in-port->fs] (get-in routes [sender out-port])
                         [in-port fs]           in-port->fs
                         f                      fs]
                     [receiver in-port f vs])]
     (reduce (fn [m [receiver in-port f vs]]
               (update-in m [receiver in-port] into (map f vs)))
             {}
             flattened)))

** Test optimizations
*** Use a record for the {:model :state :tl :tn} structure.
*** Test creating new records vs. updating properties.
*** Test pmap.
** Consider renaming afap to fast or event-driven.
** Improve debugging
*** Render network using graphviz.
*** Graphical animation
*** Stepper
    - Like prolog.
    - Step forward and back in time. Inspect states.
** demo
   - Restaurant
*** Determine how to implement a Poisson distribution for customer arrivals.
** Check that we are using the high resolution timer for the browser.
   - (now) is, but I thought there was a shim for rAF, too.
** Consider more improvements
*** Consider declaring ports in models.
    - To elucidate the interface.
    - Could this buy additional clarity in the handling of messages?
      - E.g., maybe there could be different port strategies, such as
        FIFO, or order by type.
      - We don't want to require that the update fns must be defined
        within a port-translating macro.
    - Might help catch errors.
      - Don't let something connect to a non-existent port.
    - Optimizations could use this information.
**** Proposal: Use network structure messages.
     - Adding a new model entails establishing its interface.
     - This is consistent with at least one of the dynamic structure papers.
*** Consider allowing pass thru connections for networks.
    - Can't create a "pass thru" connection where an input to :N
      connects to an output of :N.
    - I seem to recall this being explicitly disallowed in the literature, but I
      can't recall where. I'm not sure what it means to allow this.
    - This would be useful for debugging.
*** Consider deleting models where sigma = infinity and no inports.
*** Consider using monads in update fns.
    - Currently, it's annoying to have to organize the messages to
      process them efficiently. It would be nice to be able to write
      code in a straightforward way, but have it optimized
      automatically.
