
* Old code
** DEVS message passing optimization
   Didn't make a significant improvement.

          k->msg*      (reduce (fn [acc k]
                                 (let [xs (compute pkg k)]
                                   (case (count xs)
                                     0 acc
                                     1 (let [[port val] (first xs)
                                             xs (find-receivers-m P M C (P k) k port)]
                                         (case (count xs)
                                           0 acc
                                           1 (let [[k' port' t*] (first xs)
                                                   val' (reduce #(%2 %1) val t*)]
                                               (update acc k' conj [port' val']))
                                           (reduce (fn [acc [k' port' t*]]
                                                     (let [val' (reduce #(%2 %1) val t*)]
                                                       (update acc k' conj [port' val'])))
                                                   acc
                                                   xs)))
                                     (reduce (fn [acc [port val]]
                                               (let [xs (find-receivers-m P M C (P k) k port)]
                                                 (case (count xs)
                                                   0 acc
                                                   1 (let [[k' port' t*] (first xs)
                                                           val' (reduce #(%2 %1) val t*)]
                                                       (update acc k' conj [port' val']))
                                                   (reduce (fn [acc [k' port' t*]]
                                                             (let [val' (reduce #(%2 %1) val t*)]
                                                               (update acc k' conj [port' val'])))
                                                           acc
                                                           xs))))
                                             acc
                                             xs))))
                               {}
                               imminent)

** old test helper code
(defn normalize [tmsg*]
  (->> tmsg*
       (postwalk (fn [x] (if (number? x) (float x) x)))
       (map (fn [[t m]] [t (set m)]))))

(defn eq? [a b]
  (= (normalize a) (normalize b)))

(defn pprint-timestamped-msg* [tmsg*]
  (doseq [[t msg] tmsg*] (println (format "[%.3f] %s" (float t) msg))))

** switch code
;; I think this version isn't intended for Parallel DEVS

(defn switch [processing-time]
  (atomic-model
   [{:phase   :passive
     :sigma   infinity
     :inport  :in1
     :store   nil
     :switch? true} 0]
   (fn int-update [s]
     (assoc s :phase :passive :sigma infinity))
   (fn ext-update [s e x]
     (let [[port val] (first x)]
       (if (= (:phase s) :passive)
         (assoc s
                :phase  :busy
                :sigma   processing-time
                :inport  port
                :store   val
                :switch? (not (:switch? s)))
         (assoc s :sigma (- (:sigma s) e)))))
   nil
   (fn output [s]
     (case (:phase s)
       :busy (case (:switch? s)
               true (case (:inport s)
                      :in1 [[:out1 (:store s)]]
                      :in2 [[:out2 (:store s)]])
               false (case (:inport s)
                       :in1 [[:out2 (:store s)]]
                       :in2 [[:out1 (:store s)]]))))
   :sigma))


[[10 [[:in1 1]]]
 [12 [[:in1 1]]]
 [15 [[:in1 1]]]
 [20 [[:in1 1]]]
 [25 [[:in2 2]]]]

(is (eq? (-> (switch 5)
             atomic-simulator
             (afap-root-simulator 0 100)
             second)
         [[15 [[:out2 1]]]
          [20 [[:out1 1]]]
          [25 [[:out2 1]]]
          [30 [[:out2 2]]]]))


(deftest switch-test
  (let [models     {:gen-1  (generator 5 10)
                    :gen-2  (generator 5 10)
                    :switch (switch 5)}
        routes     [[:gen-1 :out :switch :in1]
                    [:gen-2 :out :switch :in2]]
        simulators {:gen-1  atomic-simulator
                    :gen-2  atomic-simulator
                    :switch atomic-simulator}
        coupled    (coupled-model models routes)
        coupled'   (assoc coupled :simulators simulators)]
    (-> coupled'
        coupled-simulator
        (afap-root-coordinator 0 100)))

  )
* DONE
** DONE Consider switching back to bags as sequences instead of maps.
   - Use group to aggregate the seq into a map for routing.

   - Performance may suffer, but probably not by much. Building maps
     for output can be more expensive than a seq.
     - e.g., (update-in s [:output :out] conj v)
       vs.   (update s :output conj [:out v])

   - The most important thing is that seqs are easier to understand.

   - Models that use labeled ports, like [:in 'x], will not be as
     simple to aggregate and dispatch on as when message bags were a
     seq.
*** Write these two helper macros to capture the two most common message processing idioms.
    - Not sure this is warranted any longer, since changing the message
      bag to a map.

    - They capture the two most common idioms.
    - They are concise. They remove boilerplate, and also the
      opportunity to make errors.
    - They clarify intent.
    - They make ports clearer.

    - I don't think there is much room for improvement over these two idioms:
      - Iterate sequentially over the bag, dispatching on port.
      - Aggregate the bag's members in one linear traversal to collect
        them, using group-by, and then handling the disjoint subsets
        however--either sequentially or in batch.
        - Note that there is only a single key-fn call on each element
          of the bag to determine which subset it belongs to. A naive
          pattern matcher would need to test each element against each
          pattern until it succeeds.

          "Partitions x by key-fn. Iterates through the clauses,
          binding x to the subset given by the corresponding key, and
          biding s to the result of the previous expr, or the original
          s, if there is no previous expr.

          Note that the expression is not evaluated if the subset is
          empty.
          "

          (dispatch* [s e x key-fn]
            key1 expr1
            key2 expr2)

          expands to

          (fn ext-update [s e x]
            (let [m (group-by key-fn x)]
              (some-> s
                (seq (m key1)) (let [x (m key1)] expr1)
                (seq (m key2)) (let [x (m key2)] expr1))))



          (dispatch [s e x key-fn]
            key1 expr1
            key2 expr2)

          expands to

          (fn ext-update [s e x]
            (reduce-kv (fn [s x]
                         (case (key-fn x)
                           key1 expr1
                           key2 expr2))
                       s
                       x))
* DEVS
** DONE Finish coupled simulator
** DONE Document examples.
** DONE Update the dynamic structure implementation.
*** DONE Re-read this: file:///home/austin/projects/tomato-system/doc/papers/VarStructDEVSXiao.pdf
    - I think we can achieve the same effect without sacrificing the separation
      of model and simulator.
      - Seems like the paper is saying that this is ok, because modelers don't
        see the implementation of "addCoupling".
      - I don't think this works for us, though, because in FP, there is no way
        for a function to effect a change on a parent like this.
    - Does it say when it makes the structure changes?
*** DONE Finish old one.
    - Clean up and check in.
*** Problem
    - Support for dynamic structure means violating core DEVS principles:
      - atomic model / coupled model separation
        - Models shouldn't have knowledge about their external network.
      - model / simulator separation
    - We're also moving this knowledge and behavior that was external to the
      system under construction, by the creator, into the system.
*** Proposal
    - Base on DSDE.
    - Implement custom simulator.
    - Determine the API.

    - The model communicates with the simulator through its API, not messages,
      which are in the model space.

    - Options:
      1. The model returns an additional value when it is updated.
      2. The model has a function that takes a state and returns structure
         change messages.
      3. The model uses an API to express structure changes.
*** Finish network
    - dynamic coupling

*** Determine how to proceed
**** Proposal: Models own their internal network.

***** How to update state?
      - If we are going to cross the model-simulation boundary, maybe we should
        drop it entirely, and use records.

        - We still want to separate the simulator behavior from the model; how?
          - There are 2 separate APIs: simulator and model.
          - We'd be moving the state over to the model, which seems fine, since
            the simulator doesn't do anything with it other than store it.

          - Even if the manager model doesn't process the messages for its
            children, its simulator does.
            - What if there was a different way to manage routing? Like, the
              model had additional functions, instead of the simulator handling
              it all.

**** DEVSJAVA
     - provides fns to update models and simulators

       - This feels off. Maybe it is tension between FP and OOP. Like, they had
         a nice declarative model and they went full OOP on it.

         - E.g., model functions call functions on the simulator. Why should
           models know anything about simulators?

**** Consider "functional devs"
     - That could be an organizing principle for this new version.
     - The idea is to adhere to the semantics of DEVS, but within an FP framework.
*** Include docs about allowed structure changes
    - See: file:///home/austin/projects/tomato-system/doc/papers/VarStructDEVSXiao.pdf
      - section 2.1
** DONE Change messages a map, where ports are keys.
   - If this is simpler and more efficient, then we definitely should do it.
   - Because order shouldn't matter.
** Implement mathematical version of DSDE.
   - Keep the whole thing as simple as possible.
   - No optimization.
*** Test it.
    - Need a model.
** Implement optimized version of DSDE.
   - As simple as it can be, while maximizing efficiency.
   - This may not resemble the examples in the DSDE paper, but it should be
     functionally the same.
** Implement flattened simulation.
   - Feel free to deviate from DSDE.
   - This should improve parallelism.
   - In the hierarchical model, getting output is interleaved with distributing
     that output locally. I think the flattened model may benefit from
     distributing all messages in one pass, rather than one network at a time.
   - Compare with not flat version.
*** Consider alternate implementation
**** graph based
     - Might be easier to understand and debug.
     - Might be able to have a receive-y-message.
       - E.g., if the graph traversal is explicit.

     - We need to be able to draw the graph.
       - This seems critical.
       - Might help w/ port api.
***** Two graphs
****** The parent/child hierarchy.
****** The network of connected ports.
**** Consider using a sorted set for queue.
** Create a dynamic example.
   - Something we can use for benchmarking.
** Improve debugging
*** Label trace with ks.
*** Indent based on depth or label each line with k
** Cleanup
*** Change network-name to N.
** Consider renaming afap to fast or event-driven.
** Create a simple benchmark.
*** Test creating new records vs. updating properties.
*** Don't factor-routes on every update.
*** Don't update network if exec didn't change.
*** Test pmap.
** Implement a RT root coordinator.
   - Refer to file:///home/austin/projects/tomato-system/doc/papers/devsjava_2005.pdf
     - p. 89
     - The root coordinator gates child processes.

   - http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.843.6421&rep=rep1&type=pdf
     - Section 4.1: How to avoid accumulating delays due to actual execution
       time.
       - See last paragraph.
** Add constructor and destructor to models.
** Add more tests.
   - Use examples.
   - Confluence tests.
   - Verify that parallel is working properly.
   - Try some tricky situations.
** Clean up
*** standardize on names
    - mail?
** update docs
*** Put this documentation somewhere

  The core of a root-simulator, but without an \"update driver\".

  This core provides a priority-queue for scheduling future events, and a step
  function to update the simulation based on the next event, which may be
  internal, external, or both simultaneously.

  A complete root-simulator implementation depends on the platform and
  requirements. Some examples:

  - An \"as-fast-as-possible\" simulator may run through an entire simulation in a single loop.
  - A Real-Time simulator might synchronize the updates with a real-time clock.
  - In the browser, a Real-Time simulator might use setInterval or updateAnimationFrame to drive the updates.
  - On the JVM, a Real-Time simulator might use threads.

  All cases need a way to schedule future events and all cases use the same
  logic for determining the next event and processing it.

  Note that \"simulator\" is synonymous with \"coordinator\". A coordinator is a
  simulator associated with a coupled model. A coupled model may also be
  referred to as a network model.

  The symbols "key", "k", "k1", etc. are synonomous with "model name".

*** Why not use protocols for models?
    - Don't know how to use a default implementation for the confluent function.
      - Note that it also depends on two of the other fn implementations.
    - The record would implement part of the simulator: maintaining state and
      tl, tn, but this would preclude flattening the network (and maybe other
      types of static analysis).
*** names
    - A model name can be anything that can be compared for equality. Keywords,
      symbols, and strings are good choices.
*** abstract simulators
    - These are meant to be mathematical structures, but we can also implement
      them. But don't get too attached to an implementation; others are always
      possible.
      - For example, we could change all the function calls to use some
        asynchronous method, and as long as we implement callbacks or whatever
        to keep the model in tact, that is ok.
*** if we do our own system
    - Say what we borrowed from where.
      - e.g., separation of model and simulator from DEVS
** Select and implement a suitable PRNG.
   - https://en.wikipedia.org/wiki/Mersenne_Twister
** Determine how to implement a Poisson distribution for customer arrivals.
** demo
   - Restaurant
** -----------------------------------------------------------------------------
** Check that we are using the high resolution timer for the browser.
   - (now) is, but I thought there was a shim for rAF, too.
** Consider declaring ports in models.
   - To elucidate the interface.
   - Could this buy additional clarity in the handling of messages?
     - E.g., maybe there could be different port strategies, such as
       FIFO, or order by type.
     - We don't want to require that the update fns must be defined
       within a port-translating macro.
   - Might help catch errors.
     - Don't let something connect to a non-existent port.
** Bug: network-model, pass thru connection
   - Can't create a "pass thru" connection where an input to :N
     connects to an output of :N.
   - I seem to recall this being explicitly disallowed in the literature, but I
     can't recall where. I'm not sure what it means to allow this.
   - This would be useful for debugging.
** Render network using graphviz.
** Consider deleting models where sigma = infinity and no inports.
** Consider using monads in update fns.
   - Currently, it's annoying to have to organize the messages to
     process them efficiently. It would be nice to be able to write
     code in a straightforward way, but have it optimized
     automatically.
** Test replaying an input history.
